#!/usr/bin/env bash
set -e

unset GEM_HOME
unset GEM_PATH
unset RUBYOPT

dir=`dirname "$0"`
cd "$dir"

if (ruby -e '') 2>/dev/null; then
	exec ruby installer.rb "$@"
else
  platform="`uname`-`uname -m`"
  if ("runtime/$platform/ruby" -e '') 2>/dev/null; then
		exec "runtime/$platform/ruby" installer.rb "$@"
	else
    echo "*** ERROR: Ruby is not installed ***" >&2
  	echo "The rbenv ruby installer is written in Ruby. This source tarball bundles precompiled versions of Ruby for many platforms for the purpose of running this installer, but unfortunately we did not include a precompiled Ruby binary for the current platform. So please install Ruby manually, then run this installer again." >&2
  	exit 10
  fi
fi
